### ISSUE TITLE
Hey Roland

### ISSUE THREAD

**Issue by m95music** [rkjoan/SkypeHub#1]
Hey rkjoan, I know they may be random but I want to know if you're still active. I've used skypehub bot 1.5 a whiiilllee ago and I recently lost it due to a HDD failure, I'm one of the beta testers if you remember, my name is Arthur if you want to look it up. Anyways, if you do see this message, I was wondering if it would be alright to download skypehub bot again?

**Comment by rkjoan** [comment]
Hello, Arthur. Thanks for asking about the project, process has been really slow here sadly... but I'd be happy to reimburse you with SkypeHUB Bot 1.6, it's the newest one I have and it should have new features :D. Enjoy beta testing and tell me how it works!

- R.K. Joan

**Comment by m95music** [comment]
Hey rkjoan, do you have any other form of communication other than here? Thanks in advance.
